### ISSUE TITLE
Schema Updates

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#27]
### Task
Update the existing schemas with the changes mentioned below.

### Details
* [x] Use the autoinc plugin for Comments like it is being used for Blogs
* [x] Update all schemas which directly or indirectly refer to comments object to 'Number' instead of `ObjectId'
* [x] Update User key in Blog Schema by adding a `ref` to `User`
* [x] Update Posts key in Tag Schema by adding a `ref` to `BlogPost`
* [x] Update Comments Schema with `ref`s to User and BlogPost
* [x] Update User Schema with `ref`s to BlogPost in Liked and Disliked Posts and similarly for Liked and Disliked Comments.

**Comment by sourabh1031** [comment]
@sakshamsaxena i would like to work on this issue

**Comment by sakshamsaxena** [comment]
@sourabh1031 You've already closed a Cakewalk issue, so you have to pick at least Intermediate ones.

**Comment by sourabh1031** [comment]
@sakshamsaxena  okay

**Comment by sakshamsaxena** [comment]
@sourabh1031 You can try this now. I've added more changes which I think are needed.

**Comment by sourabh1031** [comment]
@sakshamsaxena sorry i have not done any work today because of my health problem i will try to send to pr by tommorrow
